{{ if .Values.consul.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: consul
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1 # multiple pod for minimum HA
  selector:
    matchLabels:
      helm.stargate.spaceone.dev/service: consul
  template:
    metadata:
      labels:
{{ include "spaceone.labels" . | indent 8 }}
        helm.stargate.spaceone.dev/service: consul
    spec:
      volumes:
      - name: consul-data
        emptyDir: {}
      containers:
      - name: server
        image: consul:1.7.3 # specific tag for an image or just latest
        args:
          - consul
          - agent
          - "-server"
          - "-ui"
          - "-node=server-1"
          - "-bootstrap-expect=1"
          - "-client=0.0.0.0"
          - "-data-dir=/consul/data"

        ports:
        - name: http
          containerPort: 8500
        - name: dns
          containerPort: 8600
        volumeMounts:
        - mountPath: /consul/data
          name: consul-data
{{ end }}