{{ if .Values.consul.enabled }}
# deploying gitlab pod by Service and Pod
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: consul
  name: consul
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP # connect ClusterIP to Nginx Ingress Controller
  ports:
{{ toYaml .Values.consul.service.ports | indent 4 }}
  selector:
    helm.stargate.spaceone.dev/service: consul
{{ end }}