{{ if .Values.consul.enabled }}
# deploying gitlab pod by Service and Pod
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: consul
  name: consul
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP # connect ClusterIP to Nginx Ingress Controller
  ports:
    - name: http
      port: 80
      targetPort: 8500
      protocol: TCP

    - name: httpd
      port: 8500
      targetPort: 8500
      protocol: TCP
  selector:
    helm.stargate.spaceone.dev/service: consul
{{ end }}