{{ if .Values.supervisor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: supervisor-conf
  namespace: '{{ .Release.Namespace }}'
data:
  supervisor.yml: |
    GLOBAL:
      MAX_WORKERS: 500
      PORT: 50051
      NAME: root
      HOSTNAME: {{ .Release.Namespace }}.svc.cluster.local
      BACKEND: KubernetesConnector
      PLUGIN:
        backend: KubernetesConnector
        namespace: {{ .Release.Namespace }}
        start_port: 50051
        end_port: 50052
        headless: true
        replica:
          inventory.collector: {{ tpl .Values.supervisor.supervisor.plugin.replicas . }}

      LOG:
        loggers:
          spaceone:
            handlers:
              - console
              - file
        handlers:
          file:
            type: file
            filename: /logs/supervisor.log

      CONNECTORS:
        RepositoryConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.repository.endpoint }}
        PluginConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.plugin.endpoint }}
      QUEUES:
        default_q:
          backend: spaceone.core.queue.redis_queue.RedisQueue
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
          channel: supervisor_queue

      SCHEDULERS:
        publish:
          backend: spaceone.supervisor.scheduler.publish_scheduler.PublishScheduler
          queue: default_q
          interval: 30
        sync:
          backend: spaceone.supervisor.scheduler.sync_scheduler.SyncScheduler
          queue: default_q
          interval: 120

      WORKERS:
        worker:
          backend: spaceone.core.scheduler.worker.BaseWorker
          queue: default_q
      TOKEN_INFO:
{{ tpl (toYaml .Values.supervisor.supervisor.token) . | indent 8 }}
  liveness-probe.sh: |
    # ref: https://stackoverflow.com/a/39214806/9471220
    exec 3<>/dev/tcp/{{ .Values.redis.host }}/{{ .Values.redis.port}} && echo -e "PING\r\n" >&3 && head -c 7 <&3
{{ end }}