{{ if .Values.backend.enabled }}
{{ if .Values.backend.services.secret.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: secret
  name: secret
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - nodePort: 30055
      port: 50051
      protocol: TCP
  selector:
    app: secret
  sessionAffinity: None
  type: NodePort
{{ end }}
{{ end }}