{{ if .Values.backend.enabled }}
{{ if .Values.backend.services.secret.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: secret-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ with .Values.backend.services.secret.awsSecretManagerConnector }}
  secret-secret.yml: |
    CONNECTORS:
      AWSSecretManagerConnector:
        aws_access_key_id: {{ required "Please input your awsAccessKeyId!" .awsAccessKeyId }}
        aws_secret_access_key: {{ required "Please input your awsSecretAccessKey!" .awsSecretAccessKey }}
        region_name: {{ .regionName }}
  {{ end }}
{{ end }}
{{ end }}