{{ if .Values.backend.enabled }}
{{ if .Values.backend.services.inventory.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: inventory
  name: inventory
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - nodePort: 30054
      port: 50051
      protocol: TCP
  selector:
    app: inventory
  sessionAffinity: None
  type: NodePort
{{ end }}
{{ end }}