{{ if .Values.backend.enabled }}
{{ if .Values.backend.services.identity.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-conf
  namespace: {{ .Release.Namespace }}
data:
  identity.yml: |
    GLOBAL:
      MAX_WORKERS: 1000
      DATABASES:
        default:
          db: 'dev-identity'
          host: {{ .Values.mongo.host }}
          port: {{ .Values.mongo.port }}
          username: {{ .Values.mongo.username }}
          password: {{ .Values.mongo.password }}
      ENDPOINT:
        identity:
          endpoint: "localhost:50051"
          version: v1
      CACHES:
        default:
          backend: spaceone.core.cache.redis_cache.RedisCache
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
          db: 0
          encoding: utf-8
          socket_timeout: 10
          socket_connect_timeout: 10
      LOG:
        loggers:
          spaceone:
            handlers:
              - console
              - file
        handlers:
          file:
            type: file
            filename: /logs/identity.log
        filters:
          masking:
            rules:
              DomainOwner.create:
                - password
                - email
                - mobile
              DomainOwner.update:
                - password
                - email
                - mobile
              User.create:
                - password
                - email
                - mobile
              User.update:
                - password
                - email
                - mobile
              Token.issue:
                - credentials
      CONNECTORS:
        RepositoryConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.repository.endpoint }}
        PluginServiceConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.plugin.endpoint }}
        SecretConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.secret.endpoint }}
{{ end }}
{{ end }}