apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-spaceone-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.stargate.spaceone.dev/service: initialize-spaceone
{{ include "spaceone.labels" . | indent 4 }}
spec:
  activeDeadlineSeconds: 3000
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        helm.stargate.spaceone.dev/service: initialize-spaceone
{{ include "spaceone.labels" . | indent 8 }}
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: job-0-msa-health-check
          image: networld/grpcurl
          imagePullPolicy: Always
          # runs for 15 seconds; echoes job name and timestamp
          command:
            - sh
            - -c
            - >
              cp /grpcurl /usr/local/bin/grpcurl;
              while true;
              do

                echo GRPC HealthCheck for microservices

                ! grpcurl -plaintext {{ .Values.backend.services.config.endpoint }} spaceone.api.core.v1.ServerInfo/get_version;
                config=$?;

                ! grpcurl -plaintext {{ .Values.backend.services.identity.endpoint }} spaceone.api.core.v1.ServerInfo/get_version;
                identity=$?;

                ! grpcurl -plaintext {{ .Values.backend.services.inventory.endpoint }} spaceone.api.core.v1.ServerInfo/get_version;
                inventory=$?;

                ! grpcurl -plaintext {{ .Values.backend.services.monitoring.endpoint }} spaceone.api.core.v1.ServerInfo/get_version;
                monitoring=$?;

                ! grpcurl -plaintext {{ .Values.backend.services.repository.endpoint }} spaceone.api.core.v1.ServerInfo/get_version;
                repository=$?;

                ! grpcurl -plaintext {{ .Values.backend.services.plugin.endpoint }} spaceone.api.core.v1.ServerInfo/get_version;
                plugin=$?;

                ! grpcurl -plaintext {{ .Values.backend.services.secret.endpoint }} spaceone.api.core.v1.ServerInfo/get_version;
                secret=$?;

                ! grpcurl -plaintext {{ .Values.backend.services.statistics.endpoint }} spaceone.api.core.v1.ServerInfo/get_version;
                statistics=$?;

                if [[ $(( $config * $identity * $inventory * $monitoring * $repository * $plugin * $secret * $statistics )) -ne 0 ]];
                then
                  echo "Success. All microservices are available."
                  break;
                else
                  echo "[Error] Failed to connect some microservices"
                fi

                sleep 1;
              done
        - name: job-1-spacectl-conf-writable
          imagePullPolicy: IfNotPresent
          image: busybox
          command:
            - sh
            - -c
            - cp -r /root/initializer/spaceconfig/* /root/.spaceone
          volumeMounts:
            - mountPath: /root/.spaceone
              name: writable-spacectl-conf

            - mountPath: /root/initializer/spaceconfig/environment.yml
              name: spacectl-conf
              subPath: environment.yml
            - mountPath: /root/initializer/spaceconfig/environments/helm-root.yml
              name: spacectl-conf
              subPath: helm-root.yml

      containers:
      - name: job-2-initialize-spaceone
#        image: {{ .Values.initializer.image }}
        image: umi0410/spacectl:1.2.2
        imagePullPolicy: Always
#        imagePullPolicy: {{ .Values.initializer.imagePullPolicy}}
        command:
          - sh
          - /root/initialize.sh
        volumeMounts:
          - mountPath: /root/initialize.sh
            name: initialize-spaceone-conf
            subPath: initialize.sh

          - mountPath: /root/.spaceone
            name: writable-spacectl-conf
          - mountPath: /root/spacectl/apply
            name: spacectl-apply-conf

      volumes:
        - name: initialize-spaceone-conf
          configMap:
            name: initialize-spaceone-conf
        - name: spacectl-conf
          configMap:
            name: spacectl-conf
        - name: writable-spacectl-conf
          emptyDir: {}
        - name: spacectl-apply-conf
          configMap:
            name: spacectl-apply-conf