{{ if .Values.backend.enabled }}
{{ if .Values.backend.services.statisticsScheduler.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: statistics-scheduler-conf
  namespace: {{ .Release.Namespace }}
data:
  statistics.yml: |
    GLOBAL:
      DATABASES:
        default:
          db: 'dev-statistics'
          host: {{ .Values.mongo.host }}
          port: {{ .Values.mongo.port }}
          username: {{ .Values.mongo.username }}
          password: {{ .Values.mongo.password }}
          maxPoolSize: 200
      CACHES:
        default:
          backend: spaceone.core.cache.redis_cache.RedisCache
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
          db: 5
          encoding: utf-8
          socket_timeout: 10
          socket_connect_timeout: 10
      LOG:
        loggers:
          spaceone:
            handlers:
              - console
              - file
        handlers:
          file:
            type: file
            filename: /logs/statistics.log
      CONNECTORS:
        IdentityConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.identity.endpoint }}

        ServiceConnector:
          identity: grpc://{{ .Values.backend.services.identity.endpoint }}/v1
          inventory: grpc://{{ .Values.backend.services.inventory.endpoint }}/v1
          plugin: grpc://{{ .Values.backend.services.plugin.endpoint }}/v1
          repository: grpc://{{ .Values.backend.services.repository.endpoint }}/v1
          secret: grpc://{{ .Values.backend.services.secret.endpoint }}/v1
          monitoring: grpc://{{ .Values.backend.services.monitoring.endpoint }}/v1
      HANDLERS:
        authentication:
          - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
            uri: grpc://{{ .Values.backend.services.identity.endpoint }}/v1/Domain/get_public_key
        authorization:
          - backend: spaceone.core.handler.authorization_handler.AuthorizationGRPCHandler
            uri: grpc://{{ .Values.backend.services.identity.endpoint }}/v1/Authorization/verify
      QUEUES:
        scheduler_q:
          backend: spaceone.core.queue.redis_queue.RedisQueue
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
          channel: scheduler

      SCHEDULERS:
        hourly_scheduler:
          backend: spaceone.statistics.scheduler.stat_hourly_scheduler.StatHourlyScheduler
          queue: scheduler_q
          interval: 1
          minute: ':01'

      WORKERS:
        base_worker:
          backend: spaceone.core.scheduler.worker.BaseWorker
          queue: scheduler_q

      TOKEN_INFO:
{{ tpl (toYaml .Values.supervisor.supervisor.token) . | indent 8 }}

{{ end }}
{{ end }}