{{ if .Values.backend.enabled }}
{{ if .Values.backend.services.statisticsScheduler.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: statistics-scheduler
  name: statistics-scheduler
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - nodePort: 30062
      port: 50051
      protocol: TCP
  selector:
    app: statistics-scheduler
  sessionAffinity: None
  type: NodePort
{{ end }}
{{ end }}