{{- if .Values.frontend.enabled }}
  {{- if .Values.frontend.consoleApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- range $key, $value := .Values.frontend.consoleApi.service.annotations }}
      {{- if not (eq $key "nil") }}
    {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: console-api
  name: console-api
  namespace: {{ .Release.Namespace }}
spec:
    {{- range $key, $value := .Values.frontend.consoleApi.service.extraSpec }}
      {{- if not (eq $key "nil") }}
  {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
    {{- with .Values.frontend.consoleApi }}
  ports:
{{ toYaml .service.ports | indent 4 }}
  selector:
    helm.stargate.spaceone.dev/service: console-api
  sessionAffinity: None
  type: {{ .service.type }}
    {{- end }}
  {{- end }}
{{- end }}