{{ if .Values.mongo.initialize }}
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Values.namespace }}
  labels:
  annotations:
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db
        image: {{ .Values.mongo.image}}
        command:
          - sh
          - -c
          - sleep 8 && mongo --host {{ .Values.mongo.host }}:{{ .Values.mongo.port }} --username {{ .Values.mongo.username }} --password {{ .Values.mongo.password }} < /root/scripts/init-db.js
        volumeMounts:
          - mountPath: /root/scripts/init-db.js
            name: mongo-conf
            subPath: init-db.js

      - name: initialize
        image: {{ .Values.backend.services.identity.image }}
        command:
          - sh
          - /root/scripts/configmap/initialize.sh
        volumeMounts:
          - mountPath: /root/scripts/configmap
            name: mongo-conf
      volumes:
        - name: mongo-conf
          configMap:
            name: mongo-conf
{{ end }}