{{ if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: mongo
  name: mongo
  namespace: {{ .Release.Namespace }}
spec:
  ports:
{{ toYaml .Values.mongo.service.ports | indent 4 }}
  selector:
    helm.stargate.spaceone.dev/service: mongo
  sessionAffinity: None
  type: NodePort
{{ end }}
