{{- if .Values.backend.enabled }}
  {{- if .Values.backend.services.repository.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: repository-conf
  namespace: {{ .Release.Namespace }}
data:
  repository.yml: |
    GLOBAL:
      MAX_WORKERS: 500
      DATABASES:
        default:
          db: 'dev-repository'
          host: {{ .Values.mongo.host }}
          port: {{ .Values.mongo.port }}
          username: {{ .Values.mongo.username }}
          password: {{ .Values.mongo.password }}
      ENDPOINT:
        repository:
          endpoint: "localhost:50051"
          version: v1
      CACHES:
        default:
          backend: spaceone.core.cache.redis_cache.RedisCache
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
          db: 3
          encoding: utf-8
          socket_timeout: 10
          socket_connect_timeout: 10
      LOG:
        loggers:
          spaceone:
            handlers:
              - console
              - file
        handlers:
          file:
            type: file
            filename: /logs/repository.log
        filters:
          masking:
            rules:
              Repository.register:
                - credentials
              Repository.update:
                - credentials
      CONNECTORS:
        IdentityConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.identity.endpoint }}
        SecretConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.secret.endpoint }}
      HANDLERS:
        authentication:
        - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
          uri: grpc://{{ .Values.backend.services.identity.endpoint }}/v1/Domain/get_public_key
        authorization:
        - backend: spaceone.core.handler.authorization_handler.AuthorizationGRPCHandler
          uri: grpc://{{ .Values.backend.services.identity.endpoint }}/v1/Authorization/verify

      ROOT_TOKEN_INFO:
{{ tpl (toYaml .Values.supervisor.supervisor.token) . | indent 8 }}
  {{- end }}
{{- end }}