apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-spaceone
  namespace: {{ .Release.Namespace }}
  labels:
    helm.stargate.spaceone.dev/service: initialize-spaceone
{{ include "spaceone.labels" . | indent 4 }}
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        helm.stargate.spaceone.dev/service: initialize-spaceone
{{ include "spaceone.labels" . | indent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db
        image: {{ .Values.mongo.image}}
        command:
          - sh
          - -c
          - mongo --host {{ .Values.mongo.host }}:{{ .Values.mongo.port }} --username {{ .Values.mongo.username }} --password {{ .Values.mongo.password }} < /root/scripts/init-db.js
        volumeMounts:
          - mountPath: /root/scripts/init-db.js
            name: initializer-conf
            subPath: init-db.js

      - name: initialize
        image: {{ .Values.backend.services.identity.image }}
        command:
          - sh
          - /root/scripts/configmap/initialize.sh
        volumeMounts:
          - mountPath: /root/scripts/configmap
            name: initializer-conf
      volumes:
        - name: initializer-conf
          configMap:
            name: initializer-conf