{{- if .Values.backend.enabled }}
  {{- if .Values.backend.services.inventoryScheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: inventory-scheduler
    helm.stargate.spaceone.dev/need_initialization: "true"
  name: inventory-scheduler
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      helm.stargate.spaceone.dev/service: inventory-scheduler
  template:
    metadata:
      annotations:
        spaceone.auto-deploy-flag: {{ include (print $.Template.BasePath "/backend/inventory-scheduler/inventory-scheduler-conf.yml") . | sha256sum }}
      labels:
{{ include "spaceone.labels" . | indent 8 }}
        helm.stargate.spaceone.dev/service: inventory-scheduler
        helm.stargate.spaceone.dev/need_initialization: "true"
    spec:
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
      containers:
        - name: inventory-scheduler
          image: {{ .Values.backend.services.inventoryScheduler.image }}
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          command: ['spaceone', 'scheduler', 'spaceone.inventory']
          ports:
            - containerPort: 50051
          volumeMounts:
            - name: inventory-scheduler-conf
              mountPath: /opt/spaceone/inventory/config/inventory.yml
              subPath: inventory.yml
              readOnly: true
            - name: log-volume
              mountPath: /logs
          env:
            - name: SPACEONE_CONFIG_FILE
              value: /opt/spaceone/inventory/config/inventory.yml

      volumes:
        - name: inventory-scheduler-conf
          configMap:
            name: inventory-scheduler-conf
        - name: log-volume
          emptyDir: {}
  {{- end }}
{{- end }}