{{ if .Values.backend.enabled }}
{{ if .Values.backend.services.inventoryScheduler.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-scheduler-conf
  namespace: {{ .Release.Namespace }}
data:
  inventory.yml: |
    GLOBAL:
      MAX_WORKERS: 1000
      DATABASES:
        default:
          db: 'dev-inventory'
          host: {{ .Values.mongo.host }}
          port: {{ .Values.mongo.port }}
          username: {{ .Values.mongo.username }}
          password: {{ .Values.mongo.password }}
          maxPoolSize: 200
      ENDPOINT:
        inventory:
          endpoint: "localhost:50051"
          version: v1
      CACHES:
        default:
          backend: spaceone.core.cache.redis_cache.RedisCache
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
          db: 1
          encoding: utf-8
          socket_timeout: 10
          socket_connect_timeout: 10
      LOG:
        loggers:
          spaceone:
            handlers:
              - console
              - file
        handlers:
          file:
            type: file
            filename: /logs/inventory.log
      CONNECTORS:
        IdentityConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.identity.endpoint }}
        SecretConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.secret.endpoint }}
        PluginConnector:
          endpoint:
            v1: grpc://{{ .Values.backend.services.plugin.endpoint }}
      HANDLERS:
        authentication:
        - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
          uri: grpc://{{ .Values.backend.services.identity.endpoint }}/v1/Domain/get_public_key
        authorization:
        - backend: spaceone.core.handler.authorization_handler.AuthorizationGRPCHandler
          uri: grpc://{{ .Values.backend.services.identity.endpoint }}/v1/Authorization/verify

      QUEUES:
        collector_q:
          backend: spaceone.core.queue.redis_queue.RedisQueue
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
          channel: collector

      SCHEDULERS:
        hourly_scheduler:
          backend: spaceone.inventory.scheduler.inventory_scheduler.InventoryHourlyScheduler
          queue: collector_q
          interval: 1
          minute: ':01'
        cleanup_scheduler:
          backend: spaceone.inventory.scheduler.cleanup_scheduler.CleanupScheduler
          queue: collector_q
          interval: 1
          minute: ':05'

      TOKEN_INFO:
{{ tpl (toYaml .Values.supervisor.supervisor.token) . | indent 8 }}
{{ end }}
{{ end }}