{{ if false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spaceone.fullname" . }}
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    {{- include "spaceone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spaceone.selectorLabels" . | nindent 4 }}
{{ end }}