name: SpaceONE Review

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set environment virables
      env:
        # LOCATION points the parent directory
        LOCATION_CHART_YAML: . # optional. for pypi upload
      run: |
        echo "::set-env name=LOCATION_CHART_YAML::$LOCATION_CHART_YAML"

    - name: Set up Helm3
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Lint
      id: lint
      run: |
        helm lint .
